### ISSUE TITLE
SSL error using mailgun on laptop (works on Heroku)

### ISSUE THREAD

**Issue by rodcul** [rodcul/issues#1]
2015-05-21 08:24:03 - RestClient::SSLCertificateNotVerified - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed:

When trying to send an email using mailgun

https://github.com/rodcul/bookmark-manager/blob/master/app/controllers/email.rb

![restclient__sslcertificatenotverified_at__email_10c78b13aa949df48afdad5f7a669e56](https://cloud.githubusercontent.com/assets/782506/7744641/09d99ab8-ff9d-11e4-8632-030f0561870a.png)

**Comment by rodcul** [comment]
![restclient__sslcertificatenotverified_at__email_10c78b13aa949df48afdad5f7a669e56](https://cloud.githubusercontent.com/assets/782506/7744632/fd7b151c-ff9c-11e4-98e8-a0b7b47bc191.png)

**Comment by dwatson62** [comment]
Me too. Getting this error when sending the test message

RestClient::SSLCertificateNotVerified: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed:

**Comment by ptolemybarnes** [comment]
Hey I don't know the answer to this off the top of my head but I was just comparing with my solution from way back when, and there are some differences:
https://github.com/ptolemybarnes/ma-wk4-bookmarks-manager/blob/master/app/helpers/password_recovery_helpers.rb
I'm sending the email FROM a mailgun email account. Let me know if that helps.

**Comment by rodcul** [comment]
Hey @ptolemybarnes I got the emails sending from localhost, not sure if the way I resolved it is good practice, would appreciate feedback:
https://github.com/rodcul/bookmark-manager/commit/18604e4697e0ccfc37b18e9cc34503df9a553b47

based on: http://stackoverflow.com/questions/24881012/restclient-mailgun-error-message-from-parameter-is-missing

cc: @dwatson62

**Comment by ptolemybarnes** [comment]
Nice, the only problem is that it might be insecure. I think the problem is that Mailgun supports TLS rather than SSL. So if we can find a way to configure the rest client to use the former, it should work.
