### ISSUE TITLE
RestClient::Unauthorized at /users/reset_password 401 Unauthorized

### ISSUE THREAD

**Issue by timrobertson0122** [rodcul/issues#10]
Getting the following error at http://localhost:9393/users/reset_password when clicking on the 'Request new password' button and no amount of Googling is helping clear up what is wrong. When I navigate directly to users/reset_password the new password form shows.

/Users/makersacademy24/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb in start
          return yield(self)
/Users/makersacademy24/Projects/chitter-challenge/app/controllers/email.rb in send_email_to
      RestClient::Request.execute(
/Users/makersacademy24/Projects/chitter-challenge/app/models/user.rb in receive_password_token_email
    Chitter::Application.email_handler.send_email_to self
/Users/makersacademy24/Projects/chitter-challenge/app/controllers/users.rb in block in <class:Users>
        user.receive_password_token_email
/Users/makersacademy24/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb in service
      si.service(req, res)
/Users/makersacademy24/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb in run
          server.service(req, res)
/Users/makersacademy24/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb in block in start_thread
          block ? block.call(sock) : run(sock)
GET
No GET data.

If anyone has any ideas I'd be really grateful....

**Comment by tansaku** [comment]
hi @timrobertson0122 did this get resolved?

**Comment by timrobertson0122** [comment]
@tansaku Oddly it's now working despite not actively being resolved. I've just spammed my inbox trying to re-create the issue in order to identify the solution but to no avail.
