### ISSUE TITLE
Create a database record that includes a reference to a record in another table

### ISSUE THREAD

**Issue by DanielJohnston** [rodcul/issues#11]
This is from the Chitter Challenge, trying to save a peep to the database with a user as the 'owner' of the peep. A strict reading of the instructions is that I can just save the username as text rather than an actual link, but I'd really rather avoid that. I've got as far as looking at http://datamapper.org/docs/associations.html which has the following suggested syntax:
`comment = post.comments.create(:subject => 'DataMapper ...')`
On trying something approximating that, I'm getting a nil returned and can't see how to investigate further. Methods such as .save and .saved? cause errors as they don't apply to nil. Suggestions welcome.

**Comment by DanielJohnston** [comment]
Unrelatedly, I can't seem to add a label or milestone to the issue?!

**Comment by chidumaga** [comment]
What is the association between peep and user? If peep `belongs_to :user` then it's as simple as doing `user.peep.create`, the peep is automatically saved as belonging to the user.

**Comment by ptolemybarnes** [comment]
So Daniel and I looked over this. The issue was that the User's association with Peeps was declared as follows:

    has n, :peeps, through: Resource

This was unnecessarily creating a join table.

**Comment by DanielJohnston** [comment]
Yup, as Ptolemy said. Who knew that `through: Resource` was enough to make the join many-to-many and break everything? Marking closed now, thanks Ptolemy. :)

**Comment by DanielJohnston** [comment]
(and thanks for taking a look, Chidu!)
