### ISSUE TITLE
Cannot consistently run auto_update or auto_migrate

### ISSUE THREAD

**Issue by rodcul** [rodcul/issues#2]
Seems a bit hit and miss for me across environments & versions of code.
Have a feeling it's related to issues in my Rakefile but not sure how to fix it, would be great if someone could take a look.

https://github.com/rodcul/bookmark-manager/blob/master/Rakefile

**Comment by ptolemybarnes** [comment]
Was this what was resolved with help from Steve?

**Comment by rodcul** [comment]
guys, @stephenlloyd just resolved all my datamapper/auto_update/auto_migrate issues  by including:

```require 'data_mapper'
require_relative 'app/server'
```

at the top of the Rakefile. Basically our models were not available for the processes to run on.

**Comment by rodcul** [comment]
rake auto_migrate ENV_RACK=test
rake auto_migrate ENV_RACK=development
