### ISSUE TITLE
Deploying CSS files to Heroku [works locally]

### ISSUE THREAD

**Issue by AlexHandy1** [rodcul/issues#4]
Completed a set of css files which work locally. 
File structure at end of issue >> holding CSS files in a public directory. 

When load to heroku, all loads without an error but just get a basic html site. 

After googling get pointed towards having to set this up (https://github.com/rstacruz/sinatra-assetpack#precompile). 
Before delving into YET another set-up want to figure out if there is a simpler way to resolve. 
.
├── Gemfile
├── Gemfile.lock
├── Procfile
├── README
├── Rakefile
├── app
│   ├── bookmark_manager.rb
│   ├── controllers
│   │   ├── application.rb
│   │   ├── links.rb
│   │   ├── sessions.rb
│   │   ├── tags.rb
│   │   └── users.rb
│   ├── data_setup.rb
│   ├── helpers
│   │   ├── application.rb
│   │   └── mailgun.rb
│   ├── models
│   │   ├── link.rb
│   │   ├── tag.rb
│   │   └── user.rb
│   └── views
│       ├── index.erb
│       ├── layout.erb
│       ├── link.erb
│       ├── links
│       │   ├── new.erb
│       │   └── old_link.erb
│       ├── sessions
│       │   ├── lost.erb
│       │   ├── new.erb
│       │   └── reset.erb
│       └── users
│           └── new.erb
├── config.ru
├── public
│   └── css
│       ├── reset.css
│       └── style.css
└── spec
    ├── features
    │   ├── adding_links_spec.rb
    │   ├── forgotten_password_spec.rb
    │   ├── listing_all_links_spec.rb
    │   ├── user_management_spec.rb
    │   ├── user_sign_in_spec.rb
    │   └── user_sign_out_spec.rb
    ├── link_spec.rb
    └── spec_helper.rb

**Comment by AlexHandy1** [comment]
https://github.com/AlexHandy1/MA_week4_bookmark_manager/tree/new_structure

**Comment by rodcul** [comment]
I added
```
set :public_folder, 'public'
```

to your bookmark_manager.rb main app file at it seems to work now!
