### ISSUE TITLE
error when running Rspec on chitter_challenge - SOLVED (sort of)

### ISSUE THREAD

**Issue by bagolol** [rodcul/issues#5]
when running rspec I was getting the below error
![screen shot 2015-05-22 at 14 56 09](https://cloud.githubusercontent.com/assets/10029227/7772047/84bb608a-0093-11e5-9154-314e7acd5bf1.png)

I think the issue is that the 'test' database hasn't been initialised at this point. doing auto_migrate and auto_upgrade the db won't have any effect on the 'test' server. 
the solution @rodcul  found was to initialise the 'test' db from irb. 
=> require 'irb -r ./app/server.rb '
=> ENV['RACK_ENV'] = 'test'
=> env = ENV["RACK_ENV"] || "development"
=> DataMapper.setup(:default, "postgres://localhost/chitter_challenge_#{env}")
=> DataMapper.finalize
=> DataMapper.auto_migrate!

this works. it would be nice to understand how to have this work automatically

**Comment by rodcul** [comment]
hey @bagolol try this see if it works for you!

rake auto_upgrade ENV_RACK=test
rake auto_upgrade ENV_RACK=development
