### ISSUE TITLE
How to retrieve username for a message

### ISSUE THREAD

**Issue by rodcul** [rodcul/issues#6]
Right now I'm using:

```
2.2.1 :023 > message = Message.last(user_id: 1)
 => #<Message @id=5 @message="Add another peeeeeep!" @user_id=1>

2.2.1 :027 > User.first(id: message.user_id).username
 => "rodcul"
```

But I'm guessing there's a better way to leverage Datamappers knowledge of the relationships. Anyone have any idea?

Thanks!

**Comment by AlexHandy1** [comment]
peeps = Peep.all

peeps.each do | peep |
   peep.user.name
   peep.user.username
end

Is another way of doing what I think you're trying to do

**Comment by rodcul** [comment]
#amazeballs
