### ISSUE TITLE
Using a param in the route from a link - can it be done?

### ISSUE THREAD

**Issue by MollieS** [rodcul/issues#7]
So I'm trying to set the username of a peep as a link to the route /users/:username, which is working fine(please ignore the lack of css, that's my plan for tomorrow...):

![screen shot 2015-05-23 at 17 48 17](https://cloud.githubusercontent.com/assets/11349388/7784996/0af04ee6-0174-11e5-951d-fd1b0ba75628.png)

My issue is trying to pass the link name to the route as the parameter.  I'm sure it can be done, and it may well be beyond my capabilities at the moment, but I thought I'd try, just for fun.  

I understand that following a link will obviously not give any post data, so I'm just a little stuck on how to attempt it.  Any ideas?

**Comment by rodcul** [comment]
hey @MollieS seems like you are very close already, kinda relates to an issue @alexhandy1 solved for me this morning: https://github.com/rodcul/issues/issues/6

<a href="/users/<% peep.user.username %>"><% peep.user.username %></a>

Maybe something like this will work?
